### PR TITLE
v1.0.14 release

### PR DESCRIPTION
**Pull request by velten-dev**

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build

**Comment by velten-dev** [comment]
I'm not sure why it's failing here. I always make sure to run ```flatpak run --command=appstream-util org.flatpak.Builder validate``` on any changes I make to the appstream file. I'll try forcing the bot to build again, but may need help if it keeps failing this way.

**Comment by velten-dev** [comment]
bot, build

**Comment by barthalion** [comment]
We're in the process of replacing appstream-glib with a newer, maintained tool, which is where the failures come from.

**Comment by barthalion** [comment]
bot, build

Failed to download code from codeberg now, though

**Comment by barthalion** [comment]
Ok, we're finally on the proper error message. Landing a fix for that on our end.

```
        "W: finance.reckoner.Reckoner:8: tag-empty developer",
```

This one is legit, but codeberg isn't cooperating with me to help you pinpoint this

**Comment by barthalion** [comment]
https://codeberg.org/Reckoner/app/src/branch/main/linux/flatpak/finance.reckoner.Reckoner.appdata.xml#L8 This should be something like that:

```
<developer>
      <name>John Doe</name>
    </developer>
```

**Comment by velten-dev** [comment]
Changed appstream developer tag per Bart's suggestion. The [documentation in the builder](https://docs.flathub.org/docs/for-app-authors/linter/) still points to using developer_name, so I left that in the xml.

**Comment by velten-dev** [comment]
bot, build

**Pull request merged**
